/**
 * English titles of BeamNG.drive input actions, generated from the game's action definitions
 * (lua/ge/extensions/core/input/actions/*.json) and en-US translations of version 0.39.4.
 * Used when the install itself cannot be read; editor and debug actions are left out.
 */
export const BEAMNG_ACTION_LABELS: Record<string, string> = {
  accelerate: 'Throttle',
  accelerate_brake: 'Combined Throttle&Brake',
  accept: 'Challenge Accept Action',
  activateStarterMotor: 'Toggle Ignition State',
  appedit: 'Edit UI Apps Selector',
  bigMapControllerSelect: 'Map controller select',
  bigMapControllerZoom: 'Map zoom for controller',
  bigMapMouseClick: 'Map mouse click',
  bigMapMoveBackward: 'Map move camera backward',
  bigMapMoveForward: 'Map move camera forward',
  bigMapMoveForwardBackward: 'Map move camera forward backward',
  bigMapMoveLeft: 'Map move camera left',
  bigMapMoveLeftRight: 'Map move camera left right',
  bigMapMoveRight: 'Map move camera right',
  bigMapNextFilter: 'Next Challenge Filter',
  bigMapPreviousFilter: 'Previous Challenge Filter',
  bigMapZoom: 'Map Zoom',
  bigMapZoomIn: 'Map zoom in',
  bigMapZoomOut: 'Map zoom out',
  brake: 'Brake',
  camera_1: 'Camera 1',
  camera_10: 'Camera 10',
  camera_2: 'Camera 2',
  camera_3: 'Camera 3',
  camera_4: 'Camera 4',
  camera_5: 'Camera 5',
  camera_6: 'Camera 6',
  camera_7: 'Camera 7',
  camera_8: 'Camera 8',
  camera_9: 'Camera 9',
  cancelReplayRecording: 'Cancel recording',
  centerHeadset: 'Center VR headset',
  center_camera: 'Center Camera',
  changeCameraSpeed: 'Change camera speed',
  clutch: 'Clutch',
  couplersLock: 'Couplers: Lock all',
  couplersToggle: 'Couplers: Toggle',
  couplersUnlock: 'Couplers: Unlock all',
  cui_action_2: 'Secondary action',
  cui_action_3: 'Tertiary action',
  cui_action_4: 'Quaternary action',
  cui_advanced: 'Advanced',
  cui_camera: 'Camera',
  cui_cancel: 'Cancel',
  cui_context: 'Context menu',
  cui_details: 'Details',
  cui_logs: 'Logs',
  cui_modifier: 'Modifier',
  cui_subtab_l: 'Subtab left',
  cui_subtab_r: 'Subtab right',
  customModifier1: 'Modifier 1',
  customModifier2: 'Modifier 2',
  customModifier3: 'Modifier 3',
  customModifier4: 'Modifier 4',
  customModifier5: 'Modifier 5',
  customModifier6: 'Modifier 6',
  cycleTimeOfDay: 'Change time of day',
  decline: 'Challenge decline action',
  decreaseTwoStepRPM: 'Decrease Two-Step launch RPM',
  decrease_cc_speed: 'Decrease Cruise Control Speed (1 km/h)',
  decrease_cc_speed_large: 'Decrease Cruise Control Speed (10 km/h)',
  decrease_zoom: 'Zoom Out',
  decrease_zoom_or_freecam_down: 'Zoom Out or Freecam down',
  disable_cc: 'Disable Cruise Control',
  doBigScreenShot: 'Take Big Screenshot',
  doHugeScreenShot: 'Take Huge Screenshot',
  doScreenShot: 'Take Screenshot',
  driverZoom: 'Driver Camera Focus Zoom',
  driverZoomToggle: 'Driver Camera Focus Zoom Toggle',
  dropCameraAtPlayer: 'Drop Camera at Player',
  dropPlayerAtCamera: 'Drop Player at Camera',
  dropPlayerAtCameraNoReset: 'Drop Player at Camera without reset',
  enableHeadset: 'Enable VR headset',
  faster_motion: 'Faster motion',
  ffbForceCoefDec: 'Temporarily decrease FFB strength',
  ffbForceCoefInc: 'Temporarily increase FFB strength',
  ffbSmoothingDec: 'Temporarily decrease FFB smoothing',
  ffbSmoothingInc: 'Temporarily increase FFB smoothing',
  forceField: 'Toggle force field',
  freecamMoveBackward: 'Move camera (or seat) back',
  freecamMoveDown: 'Move camera (or seat) down',
  freecamMoveForward: 'Move camera (or seat) ahead',
  freecamMoveLeft: 'Move camera left (or tilt seat up)',
  freecamMoveRight: 'Move camera right (or tilt seat down)',
  freecamMoveUp: 'Move camera (or seat) up',
  freecamRotateHorizontal: 'Rotate Camera Horizontally',
  freecamRotateVertical: 'Rotate Camera Vertically',
  freecamSpeedDecrease: 'Change camera speed',
  freecamSpeedIncrease: 'Change camera speed',
  fuelVehicle: 'Refuel vehicle',
  funBoom: 'Explode',
  funBoost: 'Boost',
  funBoostBackwards: 'Boost Backwards',
  funBreak: 'Dismount all parts',
  funExtinguish: 'Extinguish fire',
  funFire: 'Ignite vehicle',
  funFling: 'Fling',
  funFlingDownward: 'Fling Downward',
  funHinges: 'Remove hinges',
  funRandomTire: 'Deflate random tire',
  funTires: 'Deflate all tires',
  gameplay_interact: 'Interact with gameplay',
  garageModeZoom: 'Zoom garage mode',
  gear1: '1st gear',
  gear2: '2nd gear',
  gear3: '3rd gear',
  gear4: '4th gear',
  gear5: '5th gear',
  gear6: '6th gear',
  gear7: '7th gear',
  gear8: '8th gear',
  gearN: 'Neutral position',
  gearR: 'Reverse gear',
  highbeam: 'Flash high beam headlights',
  horn: 'Horn',
  increaseTwoStepRPM: 'Increase Two-Step launch RPM',
  increase_cc_speed: 'Increase Cruise Control Speed (1 km/h)',
  increase_cc_speed_large: 'Increase Cruise Control Speed (10 km/h)',
  increase_zoom: 'Zoom In',
  increase_zoom_or_freecam_up: 'Zoom In or Freecam up',
  jumpAhead: 'Short seek ahead',
  jumpAheadFine: 'Advance one frame forward',
  jumpBack: 'Short seek back',
  jumpBackFine: 'Advance one frame backward',
  jumpFarAhead: 'Long seek ahead',
  jumpFarBack: 'Long seek back',
  latchesClose: 'Close Latches',
  latchesOpen: 'Open Latches',
  loadHome: 'Repair and recover vehicle to the saved position',
  look_back: 'Look Back',
  menu_item_back: 'Back',
  menu_item_down: 'Navigate down',
  menu_item_focus_lr: 'Focus or radial menu left/right',
  menu_item_focus_ud: 'Focus or radial menu up/down',
  menu_item_left: 'Navigate left',
  menu_item_radial_right_x: 'Scroll menu horizontally / Rotate camera X',
  menu_item_radial_right_y: 'Scroll menu vertically / Rotate camera Y',
  menu_item_right: 'Navigate right',
  menu_item_select: 'OK / Primary action',
  menu_item_up: 'Navigate up',
  menu_tab_left: 'Tab left',
  menu_tab_right: 'Tab right',
  movebackward: 'Move camera (or seat) back',
  movedown: 'Move camera (or seat) down',
  movefast: 'Move Faster',
  moveforward: 'Move camera (or seat) ahead',
  moveforwardbackward: 'Move camera (or seat) ahead',
  moveleft: 'Move camera left (or tilt seat up)',
  moveleftright: 'Move camera (or seat) left/right',
  moveright: 'Move camera right (or tilt seat down)',
  moveup: 'Move camera (or seat) up',
  nextESCMode: 'Next Drive Mode',
  nodegrabberAction: 'Hang/couple/decouple node',
  nodegrabberGrab: 'Grab focused node',
  nodegrabberPadGrab: 'Grab focused node',
  nodegrabberPadMode: 'Toggle gamepad nodegrabber mode',
  nodegrabberRender: 'Show nodegrabber nodes',
  nodegrabberStrength: 'Change nodegrabber strength',
  options: 'Options',
  overrideNitrousOxide: 'Activate Nitrous Oxide Injection',
  parkingbrake: 'Parking Brake',
  parkingbrake_temporary: 'Parking Brake (hold)',
  parkingbrake_toggle: 'Parking Brake (toggle)',
  parts_selector: 'Parts Selector',
  pause: 'Pause',
  photomode: 'Enter Photo Mode',
  photomodeDecreaseFov: 'Field of view -',
  photomodeIncreaseFov: 'Field of view +',
  photomodeMoveDown: 'Move camera (or seat) down',
  photomodeMoveForwardBackward: 'Move camera (or seat) forward/backward',
  photomodeMoveLeftRight: 'Move camera (or seat) left/right',
  photomodeMoveUp: 'Move camera (or seat) up',
  photomodeRollCameraLeft: 'Roll Camera Left',
  photomodeRollCameraRight: 'Roll Camera Right',
  pitchAbs: 'pitchAbs',
  previousESCMode: 'Previous Drive Mode',
  publishScreenShot: 'Take and Upload Screenshot',
  quit: 'Quit',
  recover_to_last_road: 'Recover vehicle to the last road',
  recover_vehicle: 'Repair / Rewind',
  recover_vehicle_alt: 'Repair / Rewind (alternate version)',
  reset_all_physics: 'Reset all vehicle physics',
  reset_cc_speed: 'Reset Cruise Control Speed',
  reset_physics: 'Restart current mission or vehicle',
  rollAbs: 'rollAbs',
  roll_camera_left: 'Roll Camera Left',
  roll_camera_right: 'Roll Camera Right',
  rotate_camera_down: 'Rotate Camera Down',
  rotate_camera_horizontal: 'Rotate Camera Horizontally',
  rotate_camera_hz_mouse: 'Rotate Camera Horizontally (RMB)',
  rotate_camera_left: 'Rotate Camera Left',
  rotate_camera_right: 'Rotate Camera Right',
  rotate_camera_up: 'Rotate Camera Up',
  rotate_camera_vertical: 'Rotate Camera Vertically',
  rotate_camera_vt_mouse: 'Rotate Camera Vertically (RMB)',
  saveHome: 'Recover Vehicle: save current position',
  setIgnitionLevel0: 'Set Ignition Level to 0',
  setIgnitionLevel1: 'Set Ignition Level to 1',
  setIgnitionLevel1Momentary: 'Set Ignition Level to 1 (Momentary)',
  setIgnitionLevel2: 'Set Ignition Level to 2',
  setIgnitionLevel2Momentary: 'Set Ignition Level to 2 (Momentary)',
  setIgnitionLevel3: 'Set Ignition Level to 3',
  setIgnitionLevel3Momentary: 'Set Ignition Level to 3 (Momentary)',
  set_cc_speed: 'Set Cruise Control Speed',
  shiftDown: 'Shift Down',
  shiftUp: 'Shift Up',
  slower_motion: 'Slower motion',
  steadycamJump: 'Steadycam jump',
  steer_left: 'Steering (left button)',
  steer_right: 'Steering (right button)',
  steering: 'Steering (axis)',
  switch_camera_next: 'Next camera',
  switch_camera_prev: 'Previous camera',
  switch_next_vehicle: 'Switch to next vehicle',
  switch_next_vehicle_multiseat: 'Switch to next vehicle (multiseat)',
  switch_previous_vehicle: 'Switch to previous vehicle',
  toggle4WDStatus: 'Toggle 4WD Status',
  toggleAITraffic: 'Toggle autonomous driving',
  toggleBigMap: 'Toggle Map',
  toggleCamera: 'Toggle Free Camera',
  toggleDiffMode: 'Toggle Differential Mode',
  toggleESCMode: 'Toggle ESC/TC Mode',
  toggleLightbarMode: 'Toggle lightbar mode',
  toggleLineLock: 'Toggle line lock',
  toggleMenues: 'Menu',
  toggleNitrousOxide: 'Toggle Nitrous Oxide Injection',
  toggleRadialMenuMulti: 'Toggle Radial Menu',
  toggleRadialMenuPlayerVehicle: 'Enter Player Vehicle Radial Menu',
  toggleRadialMenuSandbox: 'Enter Sandbox/Career/Challenge Radial Menu',
  toggleRadialMenuVehicleFeatures: 'Enter Vehicle Features Radial Menu',
  toggleRangeStatus: 'Toggle Range Status',
  toggleReplayRecording: 'Start/stop recording',
  toggleShifterMode: 'Toggle Gearbox Mode',
  toggleShowBindingsLegendApp: 'Show/Hide Bindings Legend App',
  toggleShowVehicleSpecificActions: 'Show Vehicle Specific Actions',
  toggleTraffic: 'Toggle traffic',
  toggleTransbrake: 'Toggle transbrake',
  toggleTwoStep: 'Toggle Two-Step launch logic',
  toggleUi: 'Hide UI',
  toggleVehicleTriggerCrosshairInternalCameras: 'Toggle internal camera crosshair',
  toggleVehicleTriggerCrosshairWalkingMode: 'Toggle walking mode crosshair',
  toggleWalkingMode: 'Enter/Exit vehicle',
  toggle_foglights: 'Foglights',
  toggle_fullscreen: 'Toggle Fullscreen',
  toggle_hazard_signal: 'Hazard Lights',
  toggle_headlights: 'Headlights',
  toggle_help: 'Help',
  toggle_left_signal: 'Left Signal',
  toggle_lightbar_signal: 'Lightbar Lights',
  toggle_minimap: 'Toggle minimap',
  toggle_right_signal: 'Right Signal',
  toggle_slow_motion: 'Toggle slow motion',
  toggle_underglow: 'Underglow Lights',
  triggerAction0: 'Use vehicle trigger (action 1)',
  triggerAction1: 'Use vehicle trigger (action 2)',
  triggerAction2: 'Use vehicle trigger (action 3)',
  vehicle_selector: 'Vehicle Selector',
  vehicledebugMenu: 'Parts Selector > Debug tab',
  xAxisAbs: 'xAxisAbs',
  yAxisAbs: 'yAxisAbs',
  yawAbs: 'yawAbs',
  zAxisAbs: 'zAxisAbs',
};
